version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: s3cr3t  # Replace with your desired root password
      MYSQL_DATABASE: ocr_db_api   # Replace with your database name
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_web
    command: gunicorn --bind 0.0.0.0:8000 app.wsgi:application
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
      - MYSQL_DATABASE=ocr_db_api
      - MYSQL_USER=s3cr3t
      - MYSQL_PASSWORD=ocr_db_api
      - MYSQL_HOST=db
    volumes:
      - .:/app
      - staticfiles:/app/staticfiles
      - media:/app/media

volumes:
  mysql_data:
  media:
  staticfiles: