# Generated by Django 4.2.15 on 2024-08-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='user_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
